title: Gherardo Varando
description: Gherardo personal web page
author: Gherardo Varando
plugins: 
   - jemoji

default: 
   - 
     scope:
       path: ""
       type: "pages"
     values:
       layout: "default"
